import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NextTopLoader from "nextjs-toploader";
import StoreProvider from "./StoreProvider";
import { ReactNode } from "react";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Sendeet",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: ReactNode
}
export default function RootLayout({
  children,
}: RootLayoutProps) {
  return (
    <html lang={`en`}>

      <body className={` antialiased  ${inter.className} `}>
        <NextTopLoader showSpinner={false} />
        <StoreProvider> {children}</StoreProvider>
      </body>
    </html>
  );
}
